#!/system/bin/sh

mount -o remount,rw /system
chown root.system /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chown root.system /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

chown root.system /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
chmod 664 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

mount -o remount,ro /system
